In [1]:
import pandas as pd
import numpy as np

In [59]:
dt =pd.read_csv(r"D:\Machine Learning\Sample Project1\Notes Notebooks\Working_Data\diabetes_dataset.csv")

In [3]:
dt.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [4]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [8]:
dt["smoking_history"].value_counts()

No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: smoking_history, dtype: int64

In [5]:
#Converting the Data to Numerical Understandable form!

In [13]:
X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object)
X

array([['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b',
        'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'c',
        'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'd', 'd', 'd']],
      dtype=object)

In [110]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)
fg = np.array([dt["smoking_history"].to_numpy()]).T
ohe.fit(fg)
ohe.set_output(transform="pandas")
print(ohe.n_features_in_)
print(ohe.get_feature_names_out())

1
['x0_No Info' 'x0_current' 'x0_ever' 'x0_former' 'x0_never'
 'x0_not current']

In [39]:
ohe.categories_

[array(['No Info', 'current', 'ever', 'former', 'never', 'not current'],
       dtype=object)]

In [40]:
ohe.get_feature_names_out()

array(['x0_No Info', 'x0_current', 'x0_ever', 'x0_former', 'x0_never',
       'x0_not current'], dtype=object)

In [41]:
ohe.transform(fg)

       x0_No Info  x0_current  x0_ever  x0_former  x0_never  x0_not current
0             0.0         0.0      0.0        0.0       1.0             0.0
1             1.0         0.0      0.0        0.0       0.0             0.0
2             0.0         0.0      0.0        0.0       1.0             0.0
3             0.0         1.0      0.0        0.0       0.0             0.0
4             0.0         1.0      0.0        0.0       0.0             0.0
...           ...         ...      ...        ...       ...             ...
99995         1.0         0.0      0.0        0.0       0.0             0.0
99996         1.0         0.0      0.0        0.0       0.0             0.0
99997         0.0         0.0      0.0        1.0       0.0             0.0
99998         0.0         0.0      0.0        0.0       1.0             0.0
99999         0.0         1.0      0.0        0.0       0.0             0.0

[100000 rows x 6 columns]

In [123]:
Xdf = dt["smoking_history"].to_frame()
ohdf = OneHotEncoder(sparse_output=False)
ohdf.fit(Xdf)
ohdf.set_output(transform="pandas")
ohdf.transform(Xdf)

,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...
99995,1.0,0.0,0.0,0.0,0.0,0.0
99996,1.0,0.0,0.0,0.0,0.0,0.0
99997,0.0,0.0,0.0,1.0,0.0,0.0
99998,0.0,0.0,0.0,0.0,1.0,0.0
99999,0.0,1.0,0.0,0.0,0.0,0.0

In [144]:
Xdf = dt["smoking_history"].to_frame()
ohdf = OneHotEncoder()
ohdf.fit(Xdf)
df = pd.DataFrame(ohdf.transform(Xdf))
df

                   0
0        (0, 4)\t1.0
1        (0, 0)\t1.0
2        (0, 4)\t1.0
3        (0, 1)\t1.0
4        (0, 1)\t1.0
...              ...
99995    (0, 0)\t1.0
99996    (0, 0)\t1.0
99997    (0, 3)\t1.0
99998    (0, 4)\t1.0
99999    (0, 1)\t1.0

[100000 rows x 1 columns]

In [138]:
Xdf[:,2]

InvalidIndexError: (slice(None, None, None), 2)

In [134]:
Xdf = dt["smoking_history"].to_frame()
ohdf = OneHotEncoder(sparse_output=False,drop=0)
ohdf.fit(Xdf)
ohdf.set_output(transform="pandas")
ohdf.transform(Xdf)

InvalidParameterError: The 'drop' parameter of OneHotEncoder must be a str among {'first', 'if_binary'}, an array-like or None. Got 0 instead.

In [165]:
Xdf = dt["smoking_history"].to_frame()
ohdf = OneHotEncoder(sparse_output=False,drop=["No_info"])
ohdf.fit(Xdf)
ohdf.set_output(transform="pandas")
ohdf.transform(Xdf)

ValueError: The following categories were supposed to be dropped, but were not found in the training data.
Category: 0, Feature: No_info

In [75]:
X1 = np.array([['Male', 1], ['Female', 3], ['Female', 2]])
X1

array([['Male', '1'],
       ['Female', '3'],
       ['Female', '2']], dtype='<U11')

In [111]:
ohe2 = OneHotEncoder(sparse_output=False)
ohe2.set_output(transform="pandas")
ohe2.fit(X1)
ohe2.transform(X1)
print(ohe2.n_features_in_)
print(ohe2.get_feature_names_out())

2
['x0_Female' 'x0_Male' 'x1_1' 'x1_2' 'x1_3']

In [118]:
X2 = np.array([["Male","Female","Male","Female","Male"]])
ohe3 = OneHotEncoder(sparse_output = False,categories=[2,])
ohe3.set_output(transform="pandas")
ohe3.fit_transform(X2)

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [140]:
Xdf["smoking_history"].value_counts()

No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: smoking_history, dtype: int64

In [141]:
ohe3 = OneHotEncoder(min_frequency=10000,sparse_output=False)
ohe3.fit(Xdf)
ohe3.set_output(transform="pandas")
ohe3.transform(Xdf)

,smoking_history_No Info,smoking_history_never,smoking_history_infrequent_sklearn
0,0.0,1.0,0.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,0.0,1.0
4,0.0,0.0,1.0
...,...,...,...
99995,1.0,0.0,0.0
99996,1.0,0.0,0.0
99997,0.0,0.0,1.0
99998,0.0,1.0,0.0
99999,0.0,0.0,1.0

In [163]:
X = dt.drop("diabetes",axis=1)
y = dt["diabetes"]
X["gender"].value_counts()

Female    58552
Male      41430
Other        18
Name: gender, dtype: int64

In [162]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)
clt = ColumnTransformer([("ohe",ohe,["gender","smoking_history"])],remainder="passthrough")
clt.set_output(transform="pandas")
clt.fit_transform(X)

,ohe__gender_Female,ohe__gender_Male,ohe__gender_Other,ohe__smoking_history_No Info,ohe__smoking_history_current,ohe__smoking_history_ever,ohe__smoking_history_former,ohe__smoking_history_never,ohe__smoking_history_not current,remainder__age,remainder__hypertension,remainder__heart_disease,remainder__bmi,remainder__HbA1c_level,remainder__blood_glucose_level
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,80.0,0,1,25.19,6.6,140
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,54.0,0,0,27.32,6.6,80
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28.0,0,0,27.32,5.7,158
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,36.0,0,0,23.45,5.0,155
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,76.0,1,1,20.14,4.8,155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,80.0,0,0,27.32,6.2,90
99996,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,17.37,6.5,100
99997,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,66.0,0,0,27.83,5.7,155
99998,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,24.0,0,0,35.42,4.0,100
99999,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,57.0,0,0,22.43,6.6,90

In [166]:
X

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,Female,80.0,0,1,never,25.19,6.6,140
1,Female,54.0,0,0,No Info,27.32,6.6,80
2,Male,28.0,0,0,never,27.32,5.7,158
3,Female,36.0,0,0,current,23.45,5.0,155
4,Male,76.0,1,1,current,20.14,4.8,155
...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90
99996,Female,2.0,0,0,No Info,17.37,6.5,100
99997,Male,66.0,0,0,former,27.83,5.7,155
99998,Female,24.0,0,0,never,35.42,4.0,100
99999,Female,57.0,0,0,current,22.43,6.6,90

In [167]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

oheg = OneHotEncoder(sparse_output=False)
ohes = OneHotEncoder(sparse_output=False,min_frequency=10000)

clt = ColumnTransformer([("oheg",oheg,["gender"]),
                         ("ohes",ohes,["smoking_history"])],remainder="passthrough")
clt.set_output(transform="pandas")
clt.fit(X)
clt.transform(X)

,oheg__gender_Female,oheg__gender_Male,oheg__gender_Other,ohes__smoking_history_No Info,ohes__smoking_history_never,ohes__smoking_history_infrequent_sklearn,remainder__age,remainder__hypertension,remainder__heart_disease,remainder__bmi,remainder__HbA1c_level,remainder__blood_glucose_level
0,1.0,0.0,0.0,0.0,1.0,0.0,80.0,0,1,25.19,6.6,140
1,1.0,0.0,0.0,1.0,0.0,0.0,54.0,0,0,27.32,6.6,80
2,0.0,1.0,0.0,0.0,1.0,0.0,28.0,0,0,27.32,5.7,158
3,1.0,0.0,0.0,0.0,0.0,1.0,36.0,0,0,23.45,5.0,155
4,0.0,1.0,0.0,0.0,0.0,1.0,76.0,1,1,20.14,4.8,155
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.0,0.0,0.0,1.0,0.0,0.0,80.0,0,0,27.32,6.2,90
99996,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0,0,17.37,6.5,100
99997,0.0,1.0,0.0,0.0,0.0,1.0,66.0,0,0,27.83,5.7,155
99998,1.0,0.0,0.0,0.0,1.0,0.0,24.0,0,0,35.42,4.0,100
99999,1.0,0.0,0.0,0.0,0.0,1.0,57.0,0,0,22.43,6.6,90

In [168]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

oheg = OneHotEncoder(sparse_output=False)
ohes = OneHotEncoder(sparse_output=False,min_frequency=10000)

clt = ColumnTransformer([("oheg",oheg,[0]),
                         ("ohes",ohes,[4])],remainder="passthrough")
clt.set_output(transform="pandas")
clt.fit(X)
clt.transform(X)

,oheg__gender_Female,oheg__gender_Male,oheg__gender_Other,ohes__smoking_history_No Info,ohes__smoking_history_never,ohes__smoking_history_infrequent_sklearn,remainder__age,remainder__hypertension,remainder__heart_disease,remainder__bmi,remainder__HbA1c_level,remainder__blood_glucose_level
0,1.0,0.0,0.0,0.0,1.0,0.0,80.0,0,1,25.19,6.6,140
1,1.0,0.0,0.0,1.0,0.0,0.0,54.0,0,0,27.32,6.6,80
2,0.0,1.0,0.0,0.0,1.0,0.0,28.0,0,0,27.32,5.7,158
3,1.0,0.0,0.0,0.0,0.0,1.0,36.0,0,0,23.45,5.0,155
4,0.0,1.0,0.0,0.0,0.0,1.0,76.0,1,1,20.14,4.8,155
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.0,0.0,0.0,1.0,0.0,0.0,80.0,0,0,27.32,6.2,90
99996,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0,0,17.37,6.5,100
99997,0.0,1.0,0.0,0.0,0.0,1.0,66.0,0,0,27.83,5.7,155
99998,1.0,0.0,0.0,0.0,1.0,0.0,24.0,0,0,35.42,4.0,100
99999,1.0,0.0,0.0,0.0,0.0,1.0,57.0,0,0,22.43,6.6,90